[build]
  base = "frontend/myapp"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://webservice-owyc.onrender.com/:splat"
  status = 200
  force = true
